language: cpp

os:
  - linux
  - osx

sudo: required # need by trusty
dist: trusty

compiler:
  - gcc
  - clang

cache: apt # this feature is available only for private repositories

env:
  - BTYPE="-DCMAKE_BUILD_TYPE=Debug"
  - BTYPE="-DCMAKE_BUILD_TYPE=Release"

#-------------------------------------------------------------------
# matrix details :
#
#   - 2x gcc    under Linux trusty 14.04 LTS    (debug and release)
#   - 2x clang  under Linux trusty 14.04 LTS    (debug and release)
#
#   - 2x clang  under OS X with Apple LLVM      (debug and release)
#-------------------------------------------------------------------
matrix:
  fast_finish: true
  exclude:
    - os: osx
      compiler: gcc

addons:
  apt:
    packages:
      - libboost-dev
      - libcgal-dev
      - libqt4-dev
      - libqglviewer-dev
      - libxerces-c-dev
      - libassimp-dev
      - doxygen
      - graphviz

install:
  - cmake --version
#
# osx :
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt libqglviewer xerces-c assimp doxygen graphviz; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo ln -s "/usr/local/Cellar/libqglviewer/2.6.3/lib/QGLViewer.framework" "/Library/Frameworks/QGLViewer.framework"; fi

script:
  - mkdir build && cd build && cmake .. $BTYPE
  - make
#  - make test
#
# osx only (add qt5 after qt4 in the same job) :
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew unlink qt; fi # ---> now unlink qt4
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt5; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd ..; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mkdir build_osx_qt5 && cd build_osx_qt5 && cmake .. $BTYPE -DWITH_QT5=YES -DQT5_DIR=/usr/local/opt/qt5; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make test; fi
