language: cpp

compiler:
  - gcc
  - clang

env:
  - BTYPE="-DCMAKE_BUILD_TYPE=Debug"
  - BTYPE="-DCMAKE_BUILD_TYPE=Release"

before_script:
  - sudo apt-get -qq install libboost-program-options-dev libboost-system-dev libgmp-dev libcgal-dev libqglviewer-qt4-dev libglew-dev libxerces-c-dev > apt_install

script:
  - cmake . $BTYPE
  - cmake . $BTYPE
  - make